# Generated by Django 6.0 on 2026-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_given',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
