# Generated by Django 6.0 on 2026-01-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_menuitem_stock_quantity_order_cash_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='stock_quantity',
        ),
    ]
